#cc_library(
#    name = "read_write",
#    srcs = ["read_write_asc.cpp"],
#    hdrs = ["read_write_asc.h"],
#    visibility = ["//main:__pkg__"],
#)

cc_library(
    name = "polynomial",
    hdrs = ["fit.h"],
    visibility = ["//main:__pkg__"],
)
